import React from 'react';
import { CinematicCard } from '../ui/CinematicCard';
import { Badge } from '../ui/Badge';
import { Layers } from 'lucide-react';
import { useTheme } from '../../hooks/useTheme';
import { type MaterialRequirementContract } from '../../services/api/sopApi';
import { EmptyState } from '../ui/States';

interface BomExplosionModuleProps {
  data: MaterialRequirementContract | null;
}

export const BomExplosionModule: React.FC<BomExplosionModuleProps> = ({ data }) => {
  const { mode } = useTheme();
  const isLight = mode === 'light';

  return (
    <CinematicCard
      title="Material Requirements"
      subtitle="Material requirements generated by the S&OP planning workflow."
      icon={<Layers size={18} color="#06B6D4" />}
      glowColor="cyan"
      headerAction={<Badge variant="cyan">S&OP Output</Badge>}
    >
      <div style={{ overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
          <thead>
            <tr
              style={{
                borderBottom: isLight ? '1px solid rgba(15, 23, 42, 0.1)' : '1px solid rgba(255, 255, 255, 0.08)',
                textAlign: 'left',
                color: '#64748B',
                fontSize: '11px',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
              }}
            >
              <th style={{ padding: '8px 10px' }}>Material ID</th>
              <th style={{ padding: '8px 10px' }}>Required Quantity</th>
              <th style={{ padding: '8px 10px' }}>Required Date</th>
              <th style={{ padding: '8px 10px' }}>Plant ID</th>
              <th style={{ padding: '8px 10px' }}>Priority</th>
            </tr>
          </thead>
          <tbody>
            {data ? (
              <tr
                style={{
                  borderBottom: isLight ? '1px solid rgba(15, 23, 42, 0.04)' : '1px solid rgba(255, 255, 255, 0.04)',
                }}
              >
                <td style={{ padding: '10px 10px', fontWeight: 700, color: isLight ? '#0F172A' : '#F8FAFC' }}>
                  {data.material_id}
                </td>
                <td style={{ padding: '10px 10px', color: isLight ? '#0F172A' : '#F8FAFC', fontFamily: "'JetBrains Mono', monospace" }}>
                  {data.required_quantity.toLocaleString()}
                </td>
                <td style={{ padding: '10px 10px', color: '#94A3B8', fontFamily: "'JetBrains Mono', monospace" }}>
                  {data.required_date}
                </td>
                <td style={{ padding: '10px 10px' }}>
                  <Badge variant="cyan">{data.plant_id}</Badge>
                </td>
                <td style={{ padding: '10px 10px' }}>
                  <Badge variant={data.priority === 'HIGH' ? 'rose' : (data.priority === 'MEDIUM' ? 'amber' : 'cyan')}>
                    {data.priority}
                  </Badge>
                </td>
              </tr>
            ) : (
              <tr>
                <td colSpan={5} style={{ padding: '40px 0' }}>
                  <EmptyState 
                    title="No material requirement available" 
                    message="Run S&OP to generate the current material requirement."
                  />
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </CinematicCard>
  );
};
