import React, { useState } from 'react';
import { CinematicCard } from '../ui/CinematicCard';
import { Badge } from '../ui/Badge';
import { GlowButton } from '../ui/GlowButton';
import { Sparkles, CheckCircle2, Zap } from 'lucide-react';
import { useTheme } from '../../hooks/useTheme';

interface InsightItem {
  id: string;
  title: string;
  category: string;
  description: string;
  impact: string;
  badge: 'cyan' | 'emerald' | 'amber' | 'rose';
  applied: boolean;
}

const initialInsights: InsightItem[] = [
  {
    id: 'rec-1',
    title: 'Pre-empt Tariff Increase on Organic Cotton',
    category: 'Procurement Strategy',
    description: 'Lock 25,000 kg order with Taipei Organic Fabrics before projected 4.5% tariff revision on Sept 1st.',
    impact: '+$34,200 Cost Avoidance',
    badge: 'emerald',
    applied: false,
  },
  {
    id: 'rec-2',
    title: 'Dynamic Safety Buffer Reroute',
    category: 'Risk Mitigation',
    description: 'Shift 15,000 units safety buffer from Hanoi DC to Taipei Hub due to weather warning in South China Sea.',
    impact: 'Protects 99.2% Fill Rate',
    badge: 'cyan',
    applied: false,
  },
  {
    id: 'rec-3',
    title: 'Tier-1 MOQ Batch Consolidation',
    category: 'Volume Discount',
    description: 'Combine Shenzhen production runs for Streetwear Hoodie & Tee lines to hit the 50,000-unit tier discount.',
    impact: '-$28,500 Unit Cost Savings',
    badge: 'cyan',
    applied: false,
  },
];

export const AiInsightsModule: React.FC = () => {
  const [insights] = useState(initialInsights);
  const { mode } = useTheme();
  const isLight = mode === 'light';

  return (
    <CinematicCard
      title="AI Autonomous Insights & S&OP Recommendations"
      subtitle="Prescriptive action triggers generated by Google OR-Tools and predictive ML models"
      icon={<Sparkles size={18} color="#6366F1" />}
      glowColor="indigo"
      headerAction={<Badge variant="cyan" pulse>3 Actionable Triggers</Badge>}
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {insights.map((item) => (
          <div
            key={item.id}
            style={{
              padding: '14px 16px',
              borderRadius: '10px',
              background: isLight ? 'rgba(15, 23, 42, 0.03)' : 'rgba(255, 255, 255, 0.03)',
              border: isLight ? '1px solid rgba(15, 23, 42, 0.08)' : '1px solid rgba(255, 255, 255, 0.08)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: '14px',
              flexWrap: 'wrap',
            }}
          >
            <div style={{ flex: 1, minWidth: '260px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                <span style={{ fontSize: '13px', fontWeight: 800, color: isLight ? '#0F172A' : '#F8FAFC' }}>
                  {item.title}
                </span>
                <Badge variant={item.badge}>
                  {item.category}
                </Badge>
              </div>
              <p style={{ fontSize: '12px', color: isLight ? '#475569' : '#94A3B8', lineHeight: '1.4' }}>
                {item.description}
              </p>
              <div style={{ fontSize: '11px', fontWeight: 700, color: '#16A34A', marginTop: '4px', fontFamily: "'JetBrains Mono', monospace" }}>
                Estimated Impact: {item.impact}
              </div>
            </div>

            <div style={{ flexShrink: 0 }}>
              {item.applied ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#16A34A', fontSize: '12px', fontWeight: 700 }}>
                  <CheckCircle2 size={16} />
                  <span>Applied to S&OP</span>
                </div>
              ) : (
                <GlowButton
                  variant="ghost"
                  size="sm"
                  icon={<Zap size={13} />}
                  onClick={() => {}}
                  disabled={true}
                >
                  Backend Blocked
                </GlowButton>
              )}
            </div>
          </div>
        ))}
      </div>
    </CinematicCard>
  );
};
