import type { SupplyChainNodeData } from '../types/three';

export const controlTowerNodes: SupplyChainNodeData[] = [
  {
    id: 'node-demand',
    name: '1. Demand',
    type: 'retail',
    position: [-7.2, 2.2, -2.5],
    status: 'optimal',
    capacity: 98,
    throughput: 42000,
    leadTimeDays: 0,
    riskScore: 6,
    city: 'Omnichannel POS',
    country: 'Global',
  },
  {
    id: 'node-forecast',
    name: '2. Forecast',
    type: 'factory',
    position: [-4.8, 3.4, 2.0],
    status: 'optimal',
    capacity: 96,
    throughput: 38000,
    leadTimeDays: 1,
    riskScore: 8,
    city: 'P2 LightGBM',
    country: 'Forecasting Engine',
  },
  {
    id: 'node-sop',
    name: '3. S&OP',
    type: 'warehouse',
    position: [-2.0, 3.8, -3.2],
    status: 'optimal',
    capacity: 94,
    throughput: 35000,
    leadTimeDays: 2,
    riskScore: 11,
    city: 'Buffer Balancing',
    country: 'Multi-Echelon',
  },
  {
    id: 'node-inventory',
    name: '4. Inventory',
    type: 'warehouse',
    position: [2.0, 3.8, -3.2],
    status: 'optimal',
    capacity: 92,
    throughput: 32000,
    leadTimeDays: 3,
    riskScore: 14,
    city: 'Safety Buffer Hub',
    country: 'Holding',
  },
  {
    id: 'node-production',
    name: '5. Production',
    type: 'factory',
    position: [4.8, 3.2, 2.0],
    status: 'optimal',
    capacity: 97,
    throughput: 45000,
    leadTimeDays: 5,
    riskScore: 12,
    city: 'Mega Assembly Hub',
    country: 'Manufacturing',
  },
  {
    id: 'node-materials',
    name: '6. Materials',
    type: 'supplier',
    position: [7.2, 2.0, -2.5],
    status: 'optimal',
    capacity: 90,
    throughput: 28000,
    leadTimeDays: 4,
    riskScore: 16,
    city: 'BOM Requirement',
    country: 'Fabrics & Trims',
  },
  {
    id: 'node-suppliers',
    name: '7. Suppliers',
    type: 'supplier',
    position: [6.2, -2.2, 3.0],
    status: 'warning',
    capacity: 82,
    throughput: 22000,
    leadTimeDays: 9,
    riskScore: 38,
    city: 'Tier-1 Vendor Hub',
    country: 'Global Network',
  },
  {
    id: 'node-procurement',
    name: '8. Procurement',
    type: 'factory',
    position: [0.0, -3.4, 4.0],
    status: 'optimal',
    capacity: 99,
    throughput: 50000,
    leadTimeDays: 2,
    riskScore: 7,
    city: 'PR1 MILP Solver',
    country: 'OR-Tools',
  },
  {
    id: 'node-risk',
    name: '9. Risk',
    type: 'distribution',
    position: [-6.2, -2.2, 3.0],
    status: 'warning',
    capacity: 85,
    throughput: 24000,
    leadTimeDays: 4,
    riskScore: 42,
    city: 'Disruption Radar',
    country: 'Early Warning',
  },
];


export const sopPipelineStages: SupplyChainNodeData[] = [
  {
    id: 'stage-demand',
    name: '1. Demand',
    type: 'retail',
    position: [-7.0, 2.0, 0],
    status: 'optimal',
    capacity: 98,
    throughput: 184200,
    leadTimeDays: 0,
    riskScore: 6,
    city: 'Omnichannel Signals',
    country: 'Sensing',
  },
  {
    id: 'stage-forecast',
    name: '2. Forecast',
    type: 'factory',
    position: [-4.2, 0.5, 1.5],
    status: 'optimal',
    capacity: 96,
    throughput: 181800,
    leadTimeDays: 1,
    riskScore: 8,
    city: 'LightGBM Ensemble',
    country: 'P2 ML',
  },
  {
    id: 'stage-inventory',
    name: '3. Inventory',
    type: 'warehouse',
    position: [-1.4, -1.0, -1.0],
    status: 'optimal',
    capacity: 94,
    throughput: 75000,
    leadTimeDays: 3,
    riskScore: 11,
    city: 'Safety Buffer Hub',
    country: 'Multi-Echelon',
  },
  {
    id: 'stage-production',
    name: '4. Production',
    type: 'factory',
    position: [1.4, -1.0, 1.0],
    status: 'optimal',
    capacity: 97,
    throughput: 168000,
    leadTimeDays: 5,
    riskScore: 12,
    city: 'MPS Production Run',
    country: 'Assembly',
  },
  {
    id: 'stage-capacity',
    name: '5. Capacity',
    type: 'warehouse',
    position: [4.2, 0.5, -1.5],
    status: 'optimal',
    capacity: 93,
    throughput: 195000,
    leadTimeDays: 2,
    riskScore: 14,
    city: 'Factory Line Load',
    country: 'Utilization',
  },
  {
    id: 'stage-materials',
    name: '6. Material Requirement',
    type: 'supplier',
    position: [7.0, 2.0, 0],
    status: 'optimal',
    capacity: 99,
    throughput: 248500,
    leadTimeDays: 4,
    riskScore: 9,
    city: 'BOM Explosion',
    country: 'Raw Materials',
  }
];

export const procurementSuppliers: SupplyChainNodeData[] = [
  {
    id: 'supp-taipei',
    name: 'Supplier A: Taipei Organic',
    type: 'supplier',
    position: [-6.0, 2.5, -1.0],
    status: 'optimal',
    capacity: 94,
    throughput: 48000,
    leadTimeDays: 7,
    riskScore: 6,
    city: 'Taipei',
    country: 'Taiwan (38.4% Share)',
  },
  {
    id: 'supp-shenzhen',
    name: 'Supplier B: Shenzhen Spinning',
    type: 'supplier',
    position: [-2.0, 3.5, 2.0],
    status: 'optimal',
    capacity: 98,
    throughput: 36000,
    leadTimeDays: 5,
    riskScore: 12,
    city: 'Shenzhen',
    country: 'China (28.8% Share)',
  },
  {
    id: 'supp-hanoi',
    name: 'Supplier C: Hanoi Garments',
    type: 'supplier',
    position: [2.0, 3.5, -2.0],
    status: 'warning',
    capacity: 82,
    throughput: 24000,
    leadTimeDays: 12,
    riskScore: 38,
    city: 'Hanoi',
    country: 'Vietnam (19.2% Share)',
  },
  {
    id: 'supp-frankfurt',
    name: 'Supplier D: Frankfurt Eco',
    type: 'distribution',
    position: [6.0, 2.5, 1.0],
    status: 'optimal',
    capacity: 88,
    throughput: 10000,
    leadTimeDays: 3,
    riskScore: 8,
    city: 'Frankfurt',
    country: 'Germany (8.0% Share)',
  },
  {
    id: 'supp-americas',
    name: 'Supplier E: Americas Synthetic',
    type: 'factory',
    position: [0.0, -3.2, 2.5],
    status: 'optimal',
    capacity: 90,
    throughput: 7000,
    leadTimeDays: 4,
    riskScore: 10,
    city: 'Seattle',
    country: 'USA (5.6% Share)',
  },
];
