import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Boxes, Check, ChevronDown, CircleHelp, Eye, EyeOff, Factory, LayoutDashboard, LockKeyhole, Mail, Menu, Moon, PackageCheck, Search, Settings, Sparkles, Sun, Truck, X } from 'lucide-react'
import { deriveDashboardMetrics, loadInventory, loadSuppliers } from './supabase'
import './styles.css'

const fallbackSuppliers = [
  { name: 'Mekong Apparel Co.', region: 'Ho Chi Minh, VN', category: 'Cotton jersey', score: 94, fill: 72, lead: '18 days', status: 'On track', tone: 'green' },
  { name: 'Sundara Textiles', region: 'Tiruppur, IN', category: 'Organic fleece', score: 88, fill: 58, lead: '24 days', status: 'Watch', tone: 'amber' },
  { name: 'Northstar Mills', region: 'Gaziantep, TR', category: 'Denim', score: 81, fill: 43, lead: '31 days', status: 'At risk', tone: 'red' },
  { name: 'Loom & Line', region: 'Dhaka, BD', category: 'Viscose blend', score: 86, fill: 67, lead: '21 days', status: 'On track', tone: 'green' },
]

const formatCurrency = (value) => value >= 1000000 ? `$${(value / 1000000).toFixed(2)}m` : `$${Math.round(value / 1000)}k`
const clamp = (value, minimum, maximum) => Math.min(maximum, Math.max(minimum, value))
const forecastRows = (inventory, scenario = 'Base case') => inventory.map((item, index) => {
  const uplift = scenario === 'Demand +20%' ? 1.2 : scenario === 'Promotion spike' ? 1.35 : 1
  const forecast = Math.max(12, Math.round((item.stock * (1.1 + (index % 3) * .08) + 18) * uplift))
  return { ...item, forecast, coverage: Math.round(item.stock / Math.max(1, forecast) * 30), requirement: Math.max(0, forecast - item.stock) }
})
const supplierRisk = (supplier) => clamp(Math.round((100 - supplier.score) * .65 + (100 - supplier.fill) * .25 + (parseInt(supplier.lead, 10) || 0) * .35), 4, 96)
const allocationRows = (suppliers, requirement, scenario = 'Base case') => {
  const available = scenario === 'Supplier disruption' ? suppliers.filter((supplier) => supplier.tone !== 'red') : suppliers
  const ranked = available.map((supplier) => ({ ...supplier, risk: supplierRisk(supplier), weight: Math.max(1, supplier.score * .55 + supplier.fill * .3 - (parseInt(supplier.lead, 10) || 0) * .8 - supplierRisk(supplier) * .35) })).sort((left, right) => right.weight - left.weight)
  let remaining = requirement
  return ranked.map((supplier, index) => {
    const capacity = Math.max(40, Math.round((supplier.fill / 100) * 1200))
    const quantity = index === ranked.length - 1 ? Math.min(capacity, remaining) : Math.min(capacity, Math.max(0, Math.round(requirement * supplier.weight / ranked.reduce((total, row) => total + row.weight, 0))))
    remaining -= quantity
    return { ...supplier, quantity, cost: quantity * (90 + (100 - supplier.score) * .18), feasibility: (parseInt(supplier.lead, 10) || 0) <= 24 && supplier.risk < 55 ? 'Ready' : 'Review' }
  })
}

function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [period, setPeriod] = useState('Next 90 days')
  const [scenarioRunning, setScenarioRunning] = useState(false)
  const [activeNav, setActiveNav] = useState('Overview')
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('trendwear-theme') !== 'light')
  const [toast, setToast] = useState('')
  const [suppliers, setSuppliers] = useState(fallbackSuppliers)
  const [inventory, setInventory] = useState([])
  const [dashboardMetrics, setDashboardMetrics] = useState(() => deriveDashboardMetrics(fallbackSuppliers, []))
  const [dataStatus, setDataStatus] = useState('loading')
  useEffect(() => {
    Promise.allSettled([loadSuppliers(), loadInventory()]).then(([supplierResult, inventoryResult]) => {
      const nextSuppliers = supplierResult.status === 'fulfilled' && supplierResult.value.length ? supplierResult.value : fallbackSuppliers
      const nextInventory = inventoryResult.status === 'fulfilled' ? inventoryResult.value : []
      setSuppliers(nextSuppliers)
      setInventory(nextInventory)
      setDashboardMetrics(deriveDashboardMetrics(nextSuppliers, nextInventory))
      setDataStatus(supplierResult.status === 'fulfilled' || inventoryResult.status === 'fulfilled' ? 'connected' : 'fallback')
    })
  }, [])
  const filteredSuppliers = suppliers.filter((supplier) => `${supplier.name} ${supplier.category}`.toLowerCase().includes(query.toLowerCase()))
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2800) }
  const toggleTheme = () => { const nextTheme = !darkMode; setDarkMode(nextTheme); localStorage.setItem('trendwear-theme', nextTheme ? 'dark' : 'light'); notify(`${nextTheme ? 'Dark' : 'Light'} theme enabled`) }
  const chooseNav = (label) => { setActiveNav(label); setMenuOpen(false); notify(`${label} workspace selected`) }

  if (!authenticated) return <div className="landing-video-shell"><LandingVideo /><LoginPage onLogin={() => setAuthenticated(true)} darkMode={darkMode} toggleTheme={toggleTheme} /></div>

  return <div className={`app-shell ${darkMode ? 'dark-theme' : ''}`}>
    <aside className={`sidebar ${menuOpen ? 'is-open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Sparkles size={17} /></span><span>trendwear<small>operations cloud</small></span></div>
      <button className="workspace-label" onClick={() => notify('Workspace switcher opened')}>Workspace <ChevronDown size={14} /></button>
      <nav><p className="nav-label">Command center</p><NavItem icon={<LayoutDashboard size={18} />} label="Overview" active={activeNav === 'Overview'} onClick={() => chooseNav('Overview')} /><NavItem icon={<Activity size={18} />} label="Demand signal" active={activeNav === 'Demand signal'} onClick={() => chooseNav('Demand signal')} /><NavItem icon={<Boxes size={18} />} label="Inventory" active={activeNav === 'Inventory'} onClick={() => chooseNav('Inventory')} /><NavItem icon={<Truck size={18} />} label="Procurement" badge="3" active={activeNav === 'Procurement'} onClick={() => chooseNav('Procurement')} /><NavItem icon={<Factory size={18} />} label="Suppliers" active={activeNav === 'Suppliers'} onClick={() => chooseNav('Suppliers')} /><p className="nav-label second">Workspace</p><NavItem icon={<PackageCheck size={18} />} label="Purchase orders" active={activeNav === 'Purchase orders'} onClick={() => chooseNav('Purchase orders')} /><NavItem icon={<Settings size={18} />} label="Settings" active={activeNav === 'Settings'} onClick={() => chooseNav('Settings')} /></nav><nav><NavItem icon={<ArrowUpRight size={18} />} label="Results" active={activeNav === 'Results'} onClick={() => chooseNav('Results')} /></nav>
      <div className="sidebar-foot"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><span>Planning lead</span></div><ChevronDown size={14} /></div>
    </aside>
    {menuOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setMenuOpen(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMenuOpen(true)}><Menu size={20} /></button><div className="breadcrumbs"><span>Command center</span><b>/</b><strong>{activeNav}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" title={darkMode ? 'Use light theme' : 'Use dark theme'} onClick={toggleTheme}>{darkMode ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button" aria-label="Help" onClick={() => notify('Help center is ready for your planning questions')}><CircleHelp size={19} /></button><button className="icon-button notification" aria-label="Open notifications" onClick={() => chooseNav('Notifications')}><Bell size={19} /><i /></button><button className="top-avatar" aria-label="Open profile" onClick={() => notify('Profile menu opened')}>AM</button></div></header>
      <div className="page-wrap">{activeNav === 'Overview' ? <>
        <MotionVideo page="Overview" /><section className="intro-row"><div><p className="eyebrow">Monday, 12 August 2024 <span className="live-dot" /> Live planning view</p><h1>Good morning, Alex<span>.</span></h1><p className="intro-copy">Here is the pulse of your connected supplier and inventory data.</p></div><button className={`scenario-button ${scenarioRunning ? 'running' : ''}`} onClick={() => setScenarioRunning(!scenarioRunning)}><Sparkles size={16} /> {scenarioRunning ? 'Running scenario...' : 'Run AI scenario'}</button></section>
        <section className="metric-grid"><Metric label="Inventory value" value={formatCurrency(dashboardMetrics.inventoryValue)} delta={`${inventory.length} SKUs`} note="from connected inventory" icon={<ArrowUpRight size={16} />} positive /><Metric label="Supplier reliability" value={`${dashboardMetrics.averageReliability.toFixed(1)}%`} delta={`${dashboardMetrics.averageFill.toFixed(1)}% fill`} note="network average" icon={<ArrowUpRight size={16} />} positive /><Metric label="Low-stock items" value={dashboardMetrics.lowStock} delta={dashboardMetrics.lowStock ? 'Needs review' : 'Healthy'} note="below 10 units" icon={<ArrowDownRight size={16} />} /><Metric label="Available units" value={dashboardMetrics.totalUnits.toLocaleString()} delta={`${dashboardMetrics.atRisk} at risk`} note="supplier partners" icon={<Truck size={16} />} plain /></section>
        <section className="signal-banner"><div className="signal-icon"><Sparkles size={18} /></div><div><strong>{dashboardMetrics.atRisk ? `AI signal: ${dashboardMetrics.atRisk} supplier${dashboardMetrics.atRisk === 1 ? '' : 's'} need review` : 'AI signal: supplier network is stable'}</strong><p>{dashboardMetrics.atRisk ? 'Review at-risk partners before committing new volume. This signal is calculated from current supplier status rows.' : 'No suppliers are currently marked at risk. Add forecast or order history to enable model-based recommendations.'}</p></div><button className="text-button" onClick={() => notify('Recommendation added to your action queue')}>Review recommendation <ArrowUpRight size={15} /></button></section>
        <div className="section-heading"><div><p className="eyebrow">Network health</p><h2>Supplier allocation</h2></div><div className="section-tools"><label className="search-box"><Search size={16} /><input aria-label="Search suppliers" placeholder="Search suppliers" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select value={period} onChange={(event) => setPeriod(event.target.value)} aria-label="Planning period"><option>Next 90 days</option><option>Next 30 days</option><option>Q4 plan</option></select></div></div>
        <div className="content-grid"><section className="panel allocation-panel"><div className="panel-head"><div><h3>Allocation health</h3><p>Committed volume by strategic partner</p></div><button className="more-button" aria-label="More allocation options" onClick={() => notify('Allocation options opened')}>•••</button></div><div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Reliability</th><th>Volume fill</th><th>Lead time</th><th>Status</th></tr></thead><tbody>{filteredSuppliers.map((supplier) => <tr key={supplier.name}><td><div className="supplier-cell"><span className="supplier-logo">{supplier.name.split(' ').map((word) => word[0]).join('').slice(0, 2)}</span><div><strong>{supplier.name}</strong><small>{supplier.region} · {supplier.category}</small></div></div></td><td><div className="score"><span>{supplier.score}</span><div className="score-bar"><i style={{ width: `${supplier.score}%` }} /></div></div></td><td><div className="fill-cell"><span>{supplier.fill}%</span><div className="fill-bar"><i style={{ width: `${supplier.fill}%` }} /></div></div></td><td className="muted">{supplier.lead}</td><td><span className={`status ${supplier.tone}`}><i />{supplier.status}</span></td></tr>)}</tbody></table>{filteredSuppliers.length === 0 && <div className="empty-state">No suppliers match “{query}”.</div>}</div><button className="view-all" onClick={() => notify('Supplier directory opened')}>View all suppliers <ArrowUpRight size={15} /></button></section><section className="panel attention-panel"><div className="panel-head"><div><h3>Needs attention</h3><p>Prioritized by business impact</p></div><span className="count-badge">3</span></div><div className="alert-list"><AlertItem tone="red" title="Denim cover below threshold" meta="Northstar Mills · 2 days ago" /><AlertItem tone="amber" title="PO-2048 needs confirmation" meta="Sundara Textiles · 5 hours ago" /><AlertItem tone="blue" title="Forecast signal updated" meta="Outerwear · 1 hour ago" /></div><button className="view-all" onClick={() => notify('Action queue opened')}>Open action queue <ArrowUpRight size={15} /></button></section></div>
          <SupplierAllocationSchemaTable suppliers={suppliers} query={query} />
          <OperationsSnapshot suppliers={suppliers} inventory={inventory} metrics={dashboardMetrics} notify={notify} />
        <footer><span>{dataStatus === 'connected' ? 'Backend synced just now' : dataStatus === 'loading' ? 'Connecting to backend...' : 'Demo data · backend unavailable'}</span><span className="sync-status"><i /> {dataStatus === 'connected' ? 'API connected' : 'All systems operational'}</span></footer>

      </> : <WorkspacePage page={activeNav} query={query} setQuery={setQuery} notify={notify} supplierData={suppliers} inventoryData={inventory} dashboardMetrics={dashboardMetrics} />}{toast && <div className="toast" role="status"><Sparkles size={15} />{toast}<button aria-label="Dismiss message" onClick={() => setToast('')}><X size={14} /></button></div>}
      </div>
    </main>
  </div>
}

function NavItem({ icon, label, active, badge, onClick }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}>{icon}<span>{label}</span>{badge && <b>{badge}</b>}</button> }
function Metric({ label, value, delta, note, icon, positive, plain }) { return <article className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><p className={positive ? 'positive' : plain ? 'plain' : 'negative'}>{plain ? '' : icon}{delta} <span>{note}</span></p></article> }
function AlertItem({ tone, title, meta }) { return <div className="alert-item"><span className={`alert-dot ${tone}`}><AlertTriangle size={14} /></span><div><strong>{title}</strong><small>{meta}</small></div><ArrowUpRight size={15} /></div> }
function SupplierAllocationSchemaTable({ suppliers, query }) { const rows = suppliers.filter((supplier) => `${supplier.name} ${supplier.region} ${supplier.category}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel schema-table-panel"><div className="panel-head"><div><h3>Supplier allocation data</h3><p>Exact columns from the Supabase suppliers table</p></div><span className="count-badge">{rows.length} rows</span></div><div className="table-wrap"><table><thead><tr><th>name</th><th>region</th><th>category</th><th>score</th><th>fill</th><th>lead_time_days</th><th>status</th></tr></thead><tbody>{rows.map((supplier) => <tr key={`schema-${supplier.name}`}><td><strong>{supplier.name}</strong></td><td className="muted">{supplier.region}</td><td className="muted">{supplier.category}</td><td>{supplier.score}</td><td>{supplier.fill}</td><td className="muted">{supplier.lead.replace(' days', '')}</td><td><span className={`status ${supplier.tone}`}><i />{supplier.status}</span></td></tr>)}</tbody></table>{rows.length === 0 && <div className="inventory-state">No supplier rows match your search.</div>}</div></section> }
function OperationsSnapshot({ suppliers, inventory, metrics, notify }) { const riskRows = suppliers.filter((supplier) => supplier.tone === 'red' || supplier.score < 70).sort((left, right) => left.score - right.score).slice(0, 3); const lowQuantityRows = inventory.filter((item) => item.stock < 10).sort((left, right) => left.stock - right.stock).slice(0, 3); return <section className="snapshot-grid"><article className="panel snapshot-panel"><div className="panel-head"><div><h3>Supplier risk watch</h3><p>Derived from status, score, and fill</p></div><span className="count-badge">{metrics.atRisk} risk</span></div>{riskRows.length ? <div className="watch-list">{riskRows.map((supplier) => <button key={supplier.name} className="watch-row" onClick={() => notify(`${supplier.name} selected`)}><span className="watch-mark red"><AlertTriangle size={14} /></span><span><strong>{supplier.name}</strong><small>score {supplier.score} · fill {supplier.fill}% · {supplier.lead}</small></span><ArrowUpRight size={15} /></button>)}</div> : <div className="snapshot-empty">No supplier risk rows found.</div>}</article><article className="panel snapshot-panel"><div className="panel-head"><div><h3>Inventory watch</h3><p>Rows where quantity is below 10</p></div><span className="count-badge">{metrics.lowStock} low</span></div>{lowQuantityRows.length ? <div className="watch-list">{lowQuantityRows.map((item) => <button key={item.id} className="watch-row" onClick={() => notify(`${item.title} selected`)}><span className="watch-mark amber"><Boxes size={14} /></span><span><strong>{item.title}</strong><small>sku {item.sku || '-'} · quantity {item.stock} · unit_price ${item.price.toFixed(2)}</small></span><ArrowUpRight size={15} /></button>)}</div> : <div className="snapshot-empty">No low-quantity inventory rows found.</div>}</article></section> }

function DemandPlanningPanel({ inventory, notify }) {
  const rows = forecastRows(inventory)
  const requirement = rows.reduce((total, row) => total + row.requirement, 0)
  const coverage = rows.length ? Math.round(rows.reduce((total, row) => total + row.coverage, 0) / rows.length) : 0
  return <section className="planning-stack"><div className="planning-kpis"><MiniKpi label="Forecast horizon" value="30 days" note="rolling view" /><MiniKpi label="Material gap" value={`${requirement.toLocaleString()} units`} note="net requirement" /><MiniKpi label="Avg. coverage" value={`${coverage} days`} note="on-hand supply" /></div><section className="panel planning-table"><div className="panel-head"><div><h3>Demand and material requirements</h3><p>Explainable baseline: stock velocity, current inventory, and seasonal uplift</p></div><span className="count-badge">{rows.length} styles</span></div><div className="table-wrap"><table><thead><tr><th>Style / SKU</th><th>30-day forecast</th><th>On hand</th><th>Coverage</th><th>Net requirement</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.title}</strong><small>{row.sku || 'SKU pending'}</small></td><td>{row.forecast} units</td><td>{row.stock} units</td><td><span className={`stock-value ${row.coverage < 14 ? 'low' : 'healthy'}`}>{row.coverage} days</span></td><td><strong className={row.requirement ? 'requirement-value' : 'healthy-value'}>{row.requirement.toLocaleString()} units</strong></td></tr>)}</tbody></table>{!rows.length && <div className="inventory-state">Connect inventory rows to generate the first forecast.</div>}</div><button className="view-all" onClick={() => notify('Material requirement plan added to review queue')}>Review material plan <ArrowUpRight size={15} /></button></section></section>
}

function ProcurementPlanningPanel({ suppliers, inventory, notify, scenario = 'Base case' }) {
  const requirement = forecastRows(inventory, scenario).reduce((total, row) => total + row.requirement, 0)
  const rows = allocationRows(suppliers, requirement || 480, scenario)
  const totalCost = rows.reduce((total, row) => total + row.cost, 0)
  const highRisk = rows.filter((row) => row.risk >= 55).length
  return <section className="planning-stack"><div className="planning-kpis"><MiniKpi label="Requirement" value={`${(requirement || 480).toLocaleString()} units`} note="from S&OP plan" /><MiniKpi label="Expected cost" value={formatCurrency(totalCost)} note="optimized estimate" /><MiniKpi label="Risk flagged" value={`${highRisk} suppliers`} note="needs review" /></div><section className="panel planning-table"><div className="panel-head"><div><h3>Recommended sourcing strategy</h3><p>Allocation balances supplier score, fill, lead time, capacity, and risk</p></div><span className="count-badge">{scenario}</span></div><div className="allocation-cards">{rows.map((row) => <article className="allocation-card" key={row.name}><div className="allocation-card-top"><span className="supplier-logo">{row.name.split(' ').map((word) => word[0]).join('').slice(0, 2)}</span><div><strong>{row.name}</strong><small>{row.region} · {row.lead}</small></div><span className={`status ${row.risk >= 55 ? 'red' : row.risk >= 35 ? 'amber' : 'green'}`}><i />{row.risk}% risk</span></div><div className="allocation-bar"><i style={{ width: `${requirement ? Math.min(100, row.quantity / requirement * 100) : 0}%` }} /></div><div className="allocation-card-meta"><span><b>{row.quantity.toLocaleString()}</b> units</span><span><b>${Math.round(row.cost).toLocaleString()}</b> est. cost</span><span className={row.feasibility === 'Ready' ? 'healthy-value' : 'requirement-value'}>{row.feasibility}</span></div></article>)}</div><button className="scenario-button" onClick={() => notify('Sourcing recommendation queued for approval')}><PackageCheck size={16} /> Approve sourcing recommendation</button></section></section>
}

function ScenarioPlanningPanel({ suppliers, inventory, notify }) {
  const [scenario, setScenario] = useState('Base case')
  const rows = forecastRows(inventory, scenario)
  const requirement = rows.reduce((total, row) => total + row.requirement, 0)
  const baseRequirement = forecastRows(inventory).reduce((total, row) => total + row.requirement, 0)
  const delta = requirement - baseRequirement
  return <section className="planning-stack"><section className="panel scenario-panel"><div className="scenario-controls"><div><p className="eyebrow">What-if planning</p><h3>Test a disruption before it reaches the PO</h3><p>Recalculate material gaps and supplier allocation against a changed operating condition.</p></div><label>Scenario<select value={scenario} onChange={(event) => setScenario(event.target.value)}><option>Base case</option><option>Demand +20%</option><option>Promotion spike</option><option>Supplier disruption</option></select></label></div><div className="scenario-result"><div><span>Material requirement</span><strong>{requirement.toLocaleString()} units</strong><small>{delta >= 0 ? '+' : ''}{delta.toLocaleString()} vs base plan</small></div><div><span>Supplier coverage</span><strong>{allocationRows(suppliers, requirement, scenario).reduce((total, row) => total + row.quantity, 0).toLocaleString()} units</strong><small>{scenario === 'Supplier disruption' ? 'Red-status partners excluded' : 'Capacity available'}</small></div><div><span>Decision</span><strong>{delta > 0 ? 'Rebalance buy plan' : 'Plan feasible'}</strong><small>Recommended action</small></div></div></section><ProcurementPlanningPanel suppliers={suppliers} inventory={inventory} notify={notify} scenario={scenario} /></section>
}

function MiniKpi({ label, value, note }) { return <article className="planning-kpi"><span>{label}</span><strong>{value}</strong><small>{note}</small></article> }

function DecisionChart({ page, suppliers, inventory, metrics }) {
  if (page === 'Demand signal') {
    const rows = forecastRows(inventory).slice(0, 6)
    return <section className="panel decision-chart"><div className="panel-head"><div><h3>Demand pressure by style</h3><p>Forecast demand compared with current on-hand inventory</p></div><span className="chart-legend"><i className="forecast" />forecast <i className="stock" />on hand</span></div><div className="bar-chart">{rows.map((row) => <div className="bar-row" key={row.id}><span>{row.title}</span><div className="bar-pair"><i className="forecast" style={{ width: `${Math.min(100, row.forecast / Math.max(row.forecast, row.stock, 1) * 100)}%` }} /><i className="stock" style={{ width: `${Math.min(100, row.stock / Math.max(row.forecast, row.stock, 1) * 100)}%` }} /></div><b>{row.requirement ? `+${row.requirement}` : 'covered'}</b></div>)}</div>{!rows.length && <div className="inventory-state">Connect inventory rows to visualize demand pressure.</div>}</section>
  }
  if (page === 'Inventory') {
    const rows = [...inventory].sort((left, right) => right.stock - left.stock).slice(0, 6)
    const maximum = Math.max(...rows.map((row) => row.stock), 1)
    return <section className="panel decision-chart"><div className="panel-head"><div><h3>Stock concentration</h3><p>Available units by style, highest volume first</p></div><span className="count-badge">{metrics.totalUnits.toLocaleString()} units</span></div><div className="bar-chart single-bars">{rows.map((row) => <div className="bar-row" key={row.id}><span>{row.title}</span><div className="bar-track"><i style={{ width: `${row.stock / maximum * 100}%` }} /></div><b>{row.stock.toLocaleString()}</b></div>)}</div>{!rows.length && <div className="inventory-state">Connect inventory rows to visualize stock concentration.</div>}</section>
  }
  if (page === 'Suppliers') {
    return <section className="panel decision-chart"><div className="panel-head"><div><h3>Supplier performance matrix</h3><p>Reliability and fill rate across the partner network</p></div><span className="chart-legend"><i className="score" />score <i className="fill" />fill</span></div><div className="bar-chart">{suppliers.map((supplier) => <div className="bar-row" key={supplier.name}><span>{supplier.name}</span><div className="bar-pair"><i className="score" style={{ width: `${supplier.score}%` }} /><i className="fill" style={{ width: `${supplier.fill}%` }} /></div><b>{supplierRisk(supplier)}% risk</b></div>)}</div></section>
  }
  if (page === 'Procurement' || page === 'Purchase orders') {
    const requirement = forecastRows(inventory).reduce((total, row) => total + row.requirement, 0)
    const rows = allocationRows(suppliers, requirement || 480, page === 'Purchase orders' ? 'Supplier disruption' : 'Base case')
    return <section className="panel decision-chart"><div className="panel-head"><div><h3>Recommended allocation mix</h3><p>Planned buy volume distributed across approved suppliers</p></div><span className="count-badge">{rows.reduce((total, row) => total + row.quantity, 0).toLocaleString()} units</span></div><div className="allocation-chart">{rows.map((row) => <div className="allocation-chart-row" key={row.name}><div><strong>{row.name}</strong><small>{row.risk}% risk · {row.lead}</small></div><div className="bar-track"><i style={{ width: `${requirement ? Math.min(100, row.quantity / requirement * 100) : 0}%` }} /></div><b>{row.quantity.toLocaleString()}</b></div>)}</div></section>
  }
  if (page === 'Results') return <section className="panel decision-chart"><div className="panel-head"><div><h3>Outcome scorecard</h3><p>Current decision health from connected inventory and supplier data</p></div><span className="count-badge">Live</span></div><div className="outcome-chart"><OutcomeBar label="Supplier reliability" value={metrics.averageReliability} /><OutcomeBar label="Network fill" value={metrics.averageFill} /><OutcomeBar label="Stock health" value={inventory.length ? (1 - metrics.lowStock / inventory.length) * 100 : 0} /><OutcomeBar label="Risk-free partners" value={suppliers.length ? ((suppliers.length - metrics.atRisk) / suppliers.length) * 100 : 0} /></div></section>
  return null
}

function OutcomeBar({ label, value }) { return <div className="outcome-row"><span>{label}</span><div className="bar-track"><i style={{ width: `${clamp(value, 0, 100)}%` }} /></div><b>{Math.round(value)}%</b></div> }

function WorkspacePage({ page, query, setQuery, notify, supplierData, inventoryData, dashboardMetrics }) {
  const pageData = {
    'Demand signal': { eyebrow: 'Forecast intelligence', title: 'Demand signal', copy: 'Translate current stock into an explainable rolling demand plan and material requirement.', icon: <Activity size={20} />, metrics: [['Forecast horizon', '30 days', 'Rolling', 'baseline forecast'], ['Material gap', 'Calculated', 'From inventory', 'net requirement'], ['Planning status', 'Live', 'Explainable', 'stock velocity']] },
    Inventory: { eyebrow: 'Stock position', title: 'Inventory control', copy: 'Keep every style in motion with quantities and unit values from your connected inventory table.', icon: <Boxes size={20} />, metrics: [['Available units', dashboardMetrics.totalUnits.toLocaleString(), `${inventoryData.length} SKUs`, 'from inventory'], ['Inventory value', formatCurrency(dashboardMetrics.inventoryValue), 'Calculated', 'quantity x unit price'], ['Low-stock items', String(dashboardMetrics.lowStock), dashboardMetrics.lowStock ? 'Needs review' : 'Healthy', 'below 10 units']] },
    Procurement: { eyebrow: 'Buy plan', title: 'Procurement workspace', copy: 'Allocate the material requirement across approved suppliers while controlling cost, lead time, quality, and risk.', icon: <Truck size={20} />, metrics: [['Requirement', 'Calculated', 'From S&OP', 'material need'], ['Expected cost', 'Optimized', 'Weighted objective', 'cost and delay'], ['Risk control', 'Active', 'Supplier score', 'pre-PO visibility']] },
    Suppliers: { eyebrow: 'Partner network', title: 'Supplier directory', copy: 'A clear view of partner performance, capacity, and exposure from your connected suppliers table.', icon: <Factory size={20} />, metrics: [['Active partners', String(supplierData.length), 'Connected', 'supplier rows'], ['Avg. reliability', `${dashboardMetrics.averageReliability.toFixed(1)}%`, `${dashboardMetrics.averageFill.toFixed(1)}% fill`, 'network average'], ['Risk flagged', String(dashboardMetrics.atRisk), dashboardMetrics.atRisk ? 'Needs review' : 'Healthy', 'status rows']] },
    'Purchase orders': { eyebrow: 'Scenario simulator', title: 'Scenario simulator', copy: 'Stress-test demand, capacity, promotion, and supplier disruption before committing the buy plan.', icon: <PackageCheck size={20} />, metrics: [['Base plan', 'Ready', 'Inventory-led', 'current position'], ['Scenarios', '4', 'Interactive', 'what-if cases'], ['Decision support', 'Live', 'Risk-aware', 'recommended action']] },
    Notifications: { eyebrow: 'Command center', title: 'Notifications', copy: 'Notifications will appear when an alerts table or backend event stream is connected.', icon: <Bell size={20} />, metrics: [['Unread alerts', 'Not configured', 'Needs data', 'alerts table'], ['Updated today', 'Not configured', 'Needs data', 'event history'], ['Response rate', 'Not configured', 'Needs data', 'activity history']] },
    Results: { eyebrow: 'Measured outcomes', title: 'Planning results', copy: 'Measure the current state of your supplier and inventory network from connected Supabase rows.', icon: <ArrowUpRight size={20} />, metrics: [['Inventory value', formatCurrency(dashboardMetrics.inventoryValue), 'Calculated', 'unit_price x quantity'], ['Supplier score', `${dashboardMetrics.averageReliability.toFixed(1)}%`, 'Average', 'score'], ['Stock coverage', `${dashboardMetrics.totalUnits.toLocaleString()} units`, `${dashboardMetrics.lowStock} low`, 'quantity'], ['Risk exposure', `${dashboardMetrics.atRisk} suppliers`, dashboardMetrics.atRisk ? 'Review' : 'Healthy', 'status']] },
    Settings: { eyebrow: 'Workspace setup', title: 'Settings', copy: 'Workspace settings will appear when authentication and team configuration are connected.', icon: <Settings size={20} />, metrics: [['Planning cadence', 'Not configured', 'Needs backend', 'workspace settings'], ['Team members', 'Not configured', 'Needs auth', 'team management'], ['Data connections', '2 tables', 'Connected', 'Supabase']] },
  }[page]
  return <>
    <MotionVideo page={page} /><section className="workspace-hero"><div className="workspace-hero-icon">{pageData.icon}</div><div><p className="eyebrow">{pageData.eyebrow}</p><h1>{pageData.title}<span>.</span></h1><p className="intro-copy">{pageData.copy}</p></div><button className="scenario-button" onClick={() => notify(`${page} action started`)}><Sparkles size={16} /> Take action</button></section>
    <section className="metric-grid page-metrics">{pageData.metrics.map(([label, value, delta, note]) => <PageMetric key={label} label={label} value={value} delta={delta} note={note} />)}</section><DecisionChart page={page} suppliers={supplierData} inventory={inventoryData} metrics={dashboardMetrics} />
    <div className="section-heading"><div><p className="eyebrow">Live workspace</p><h2>{page === 'Suppliers' ? 'Partner performance' : 'Priority signals'}</h2></div><label className="search-box"><Search size={16} /><input aria-label={`Search ${page}`} placeholder={`Search ${page.toLowerCase()}`} value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>
    {page === 'Results' && <ResultsPage suppliers={supplierData} inventory={inventoryData} metrics={dashboardMetrics} />}{page === 'Suppliers' && <SupplierTable suppliers={supplierData} query={query} notify={notify} />}{page === 'Inventory' && <DashboardTable products={inventoryData} metrics={dashboardMetrics} />}{page === 'Demand signal' && <DemandPlanningPanel inventory={inventoryData} notify={notify} />}{page === 'Procurement' && <ProcurementPlanningPanel suppliers={supplierData} inventory={inventoryData} notify={notify} />}{page === 'Purchase orders' && <ScenarioPlanningPanel suppliers={supplierData} inventory={inventoryData} notify={notify} />}{!['Suppliers', 'Inventory', 'Results', 'Demand signal', 'Procurement', 'Purchase orders'].includes(page) && <CapabilityPanel page={page} notify={notify} />}
  </>
}

function SupplierTable({ suppliers, query, notify }) { const rows = suppliers.filter((supplier) => `${supplier.name} ${supplier.category} ${supplier.region}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel page-table-panel"><div className="panel-head"><div><h3>Supplier health</h3><p>Live rows from Supabase: name, region, category, score, fill, lead_time_days, status</p></div><span className="count-badge">{rows.length} shown</span></div><div className="table-wrap"><table><thead><tr><th>name</th><th>category</th><th>score</th><th>fill</th><th>lead_time_days</th><th>status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.name}><td><div className="supplier-cell"><span className="supplier-logo">{row.name.split(' ').map((word) => word[0]).join('').slice(0, 2)}</span><div><strong>{row.name}</strong><small>{row.region}</small></div></div></td><td className="muted">{row.category}</td><td><div className="score"><span>{row.score}</span><div className="score-bar"><i style={{ width: `${row.score}%` }} /></div></div></td><td className="muted">{row.fill}%</td><td className="muted">{row.lead}</td><td><span className={`status ${row.tone}`}><i />{row.status}</span></td></tr>)}</tbody></table>{rows.length === 0 && <div className="inventory-state">No supplier rows match your search.</div>}</div><button className="view-all" onClick={() => notify('Supplier report export is ready to configure')}>Export supplier report <ArrowUpRight size={15} /></button></section> }

function CapabilityPanel({ page, notify }) { return <section className="panel capability-panel"><div className="capability-icon"><Sparkles size={18} /></div><div><h3>{page} backend not connected</h3><p>This workspace is ready for its data contract. Connect the required Supabase table or ML endpoint before showing operational values.</p><button className="text-button" onClick={() => notify(`${page} integration requirements opened`)}>View integration requirements <ArrowUpRight size={15} /></button></div></section> }

function ResultsPage({ suppliers, inventory, metrics }) { const supplierHealth = Math.round((metrics.averageReliability + metrics.averageFill) / 2); const stockHealth = inventory.length ? Math.max(0, Math.round((1 - metrics.lowStock / inventory.length) * 100)) : 0; return <section className="results-grid"><article className="panel result-panel"><div className="result-orbit"><span /></div><div><p className="eyebrow">Current measurement</p><h3>Network health score</h3><strong className="result-score">{Math.round((supplierHealth + stockHealth) / 2)}<small>/100</small></strong><p>Calculated from supplier score, fill, and inventory quantity.</p></div></article><article className="panel result-panel"><div className="panel-head"><div><h3>KPI measurements</h3><p>Current values from Supabase</p></div><span className="count-badge">Live</span></div><div className="kpi-measurements"><KpiMeasurement label="supplier score" value={metrics.averageReliability} tone="green" /><KpiMeasurement label="fill" value={metrics.averageFill} tone="lime" /><KpiMeasurement label="stock health" value={stockHealth} tone="amber" /><KpiMeasurement label="risk-free partners" value={suppliers.length ? ((suppliers.length - metrics.atRisk) / suppliers.length) * 100 : 0} tone="coral" /></div></article></section> }

function KpiMeasurement({ label, value, tone }) { return <div className="kpi-measurement"><div><span>{label}</span><strong>{Math.round(value)}%</strong></div><div className="kpi-track"><i className={tone} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div></div> }

function MotionVideo({ page }) { return <div className={`motion-video motion-${page.toLowerCase().replaceAll(' ', '-')}`} aria-hidden="true"><video autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1600&q=80"><source src="https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4" type="video/mp4" /></video><span className="motion-video-shade" /><span className="motion-grid" /><span className="motion-shelf shelf-one" /><span className="motion-shelf shelf-two" /><span className="motion-box box-one" /><span className="motion-box box-two" /><span className="motion-box box-three" /><span className="motion-line one" /><span className="motion-line two" /><span className="motion-orb" /><span className="motion-scan" /><strong>SUPPLY FLOW</strong><small>LIVE INVENTORY / {page.toUpperCase()}</small></div> }
function LandingVideo() { return <div className="landing-video" aria-hidden="true"><video autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1600&q=85"><source src="https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4" type="video/mp4" /></video><span>WAREHOUSE OPERATIONS / LIVE</span></div> }

function PageMetric({ label, value, delta, note }) { return <article className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon"><ArrowUpRight size={16} /></span></div><strong>{value}</strong><p className="positive">{delta} <span>{note}</span></p></article> }

function DashboardTable({ products, metrics }) {
  return <section className="panel inventory-panel"><div className="panel-head"><div><h3>Inventory dashboard</h3><p>Live rows from Supabase: product_name, sku, unit_price, quantity</p></div><span className="count-badge">{products.length} items</span></div><div className="inventory-summary"><span><strong>{metrics.totalUnits.toLocaleString()}</strong> quantity</span><span><strong>{formatCurrency(metrics.inventoryValue)}</strong> unit_price value</span><span><strong>{metrics.lowStock}</strong> low quantity</span></div><div className="table-wrap"><table><thead><tr><th>id</th><th>product_name</th><th>sku</th><th>unit_price</th><th>quantity</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td className="muted">{product.id}</td><td><strong>{product.title}</strong></td><td className="muted">{product.sku || '-'}</td><td>${product.price.toFixed(2)}</td><td><span className={`stock-value ${product.stock < 10 ? 'low' : 'healthy'}`}>{product.stock}</span></td></tr>)}</tbody></table>{products.length === 0 && <div className="inventory-state">No inventory rows found in Supabase.</div>}</div></section>
}

function AuthLoginPage({ onPasswordLogin, onGoogleLogin, onPasswordReset, darkMode, toggleTheme }) {
  const [email, setEmail] = useState('alex.morgan@trendwear.com')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [resetMessage, setResetMessage] = useState('')
  const submit = async (event) => {
    event.preventDefault()
    if (!email || !password) { setError('Enter your work email and password to continue.'); return }
    setLoading(true)
    setError('')
    try { await onPasswordLogin(email, password) } catch (authError) { setError(authError.message || 'Authentication failed. Please try again.') } finally { setLoading(false) }
  }
  const googleLogin = async () => { setLoading(true); setError(''); try { await onGoogleLogin() } catch (authError) { setError(authError.message || 'Google sign-in failed. Please try again.'); setLoading(false) } }
  const passwordReset = async () => { setLoading(true); setError(''); setResetMessage(''); try { await onPasswordReset(email); setResetMessage('Reset instructions sent. Check your inbox.') } catch (authError) { setError(authError.message || 'Could not send reset instructions.') } finally { setLoading(false) } }
  return <div className={`login-shell ${darkMode ? 'dark-theme' : ''}`}>
    <div className="login-art"><div className="login-brand"><span className="brand-mark"><Sparkles size={17} /></span><span>trendwear<small>operations cloud</small></span></div><div className="art-copy"><p className="eyebrow">The intelligent supply network</p><h1>Make every<br /><em>move</em> count.</h1><p>One clear view of demand, inventory, and supplier risk for teams that move fashion forward.</p><div className="art-stats"><div><strong>96.8%</strong><span>service level</span></div><div><strong>18</strong><span>active partners</span></div><div><strong>91.4%</strong><span>forecast accuracy</span></div></div></div><div className="art-foot"><span><Check size={14} /> Plans aligned in real time</span><span>TrendWear / 2024</span></div></div>
    <main className="login-panel"><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme" title={darkMode ? 'Use light theme' : 'Use dark theme'}>{darkMode ? <Sun size={17} /> : <Moon size={17} />}</button><div className="login-form-wrap"><div className="mobile-login-brand"><span className="brand-mark"><Sparkles size={17} /></span><b>TRENDWEAR AI</b></div><p className="eyebrow">Welcome back</p><h2>Sign in to your<br /><span>planning workspace.</span></h2><p className="login-subtitle">Your supply network is ready when you are.</p><form onSubmit={submit}><label>Work email<div className="input-wrap"><Mail size={16} /><input type="email" value={email} onChange={(event) => { setEmail(event.target.value); setError(''); setResetMessage('') }} placeholder="you@company.com" autoComplete="email" /></div></label><label>Password<div className="input-wrap"><LockKeyhole size={16} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => { setPassword(event.target.value); setError('') }} placeholder="Enter your password" autoComplete="current-password" /><button type="button" className="field-action" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><div className="form-options"><label className="remember"><input type="checkbox" defaultChecked /> <span>Remember me</span></label><button type="button" className="forgot" onClick={passwordReset} disabled={loading}>Forgot password?</button></div>{error && <p className="form-error" role="alert">{error}</p>}{resetMessage && <p className="form-success" role="status">{resetMessage}</p>}<button className="login-button" type="submit" disabled={loading}>{loading ? 'Signing in...' : 'Enter workspace'} {!loading && <ArrowRight size={16} />}</button></form><div className="login-divider"><span>or continue with</span></div><button className="sso-button" type="button" onClick={googleLogin} disabled={loading}><span className="sso-mark">G</span> Continue with Google</button><p className="login-legal">By continuing, you agree to TrendWear's terms and privacy policy.</p></div><p className="login-footer">Need access? <button type="button" onClick={() => setError('Invite requests are coming soon.')}>Request an invite <ArrowUpRight size={13} /></button></p></main>
  </div>
}

function LoginPage({ onLogin, darkMode, toggleTheme }) {
  const [email, setEmail] = useState('alex.morgan@trendwear.com')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState('')
  const submit = (event) => { event.preventDefault(); if (!email || !password) { setError('Enter your work email and password to continue.'); return } onLogin() }
  return <div className={`login-shell ${darkMode ? 'dark-theme' : ''}`}>
    <div className="login-art"><div className="login-brand"><span className="brand-mark"><Sparkles size={17} /></span><span>trendwear<small>operations cloud</small></span></div><div className="art-copy"><p className="eyebrow">The intelligent supply network</p><h1>Make every<br /><em>move</em> count.</h1><p>One clear view of demand, inventory, and supplier risk for teams that move fashion forward.</p><div className="art-stats"><div><strong>2</strong><span>connected tables</span></div><div><strong>Live</strong><span>supplier data</span></div><div><strong>Ready</strong><span>for ML inputs</span></div></div></div><div className="art-foot"><span><Check size={14} /> Supabase connection ready</span><span>TrendWear / 2024</span></div></div>
    <main className="login-panel"><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme" title={darkMode ? 'Use light theme' : 'Use dark theme'}>{darkMode ? <Sun size={17} /> : <Moon size={17} />}</button><div className="login-form-wrap"><div className="mobile-login-brand"><span className="brand-mark"><Sparkles size={17} /></span><b>trendwear</b></div><p className="eyebrow">Welcome back</p><h2>Sign in to your<br /><span>planning workspace.</span></h2><p className="login-subtitle">Your supply network is ready when you are.</p><form onSubmit={submit}><label>Work email<div className="input-wrap"><Mail size={16} /><input type="email" value={email} onChange={(event) => { setEmail(event.target.value); setError('') }} placeholder="you@company.com" /></div></label><label>Password<div className="input-wrap"><LockKeyhole size={16} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => { setPassword(event.target.value); setError('') }} placeholder="Enter your password" /><button type="button" className="field-action" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><div className="form-options"><label className="remember"><input type="checkbox" defaultChecked /> <span>Remember me</span></label><button type="button" className="forgot" onClick={() => setError('Password reset instructions are coming soon.')}>Forgot password?</button></div>{error && <p className="form-error">{error}</p>}<button className="login-button" type="submit">Enter workspace <ArrowRight size={16} /></button></form><div className="login-divider"><span>or continue with</span></div><button className="sso-button" type="button" onClick={onLogin}><span className="sso-mark">G</span> Continue with Google</button><p className="login-legal">By continuing, you agree to TrendWear's <button type="button" onClick={() => setError('Terms are available from your workspace administrator.')}>terms</button> and <button type="button" onClick={() => setError('Privacy details are available from your workspace administrator.')}>privacy policy</button>.</p></div><footer className="login-footer">Need access? <button type="button" onClick={() => setError('Ask your workspace administrator for an invite.')}>Request an invite <ArrowUpRight size={13} /></button></footer></main>
  </div>
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)